# Generated by Django 4.1.1 on 2022-09-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_rename_tag_scope_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
